---

- name: Ensure sudo group is present
  group:
    name: sudo
    state: present
  become: true

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "visudo -cf %s"
  become: true

- name: Add new super user
  user:
    name: "{{ user }}"
    password: "{{ password }}"
    groups: sudo
    append: yes
    state: present
    shell: /bin/bash
    update_password: always
  become: true

- name: Add ssh key for new super user
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', public_key) }}"
  become: true
