---

- name: Backup db
  shell: php artisan backup:run
  args:
    chdir: "{{ new_release_dir }}"
  when: backup_db

- name: Run migrations
  shell: "{{ migrate_command | default('php artisan migrate --force') }}"
  args:
    chdir: "{{ new_release_dir }}"
  register: migrations_output
  when: migrate
